management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 1111
spring:
  application:
    name: WELCOME-API
  boot:
    admin:
      client:
        url: http://localhost:8081/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Shiva@212
    url: jdbc:mysql://localhost:3306/MICROSERVICESIRCTC
    username: root
  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
       matching-strategy: ant-path-matcher
